"""Optional cache backends that wrap third-party Python libs."""
from __future__ import annotations
from typing import Any


class GPTCacheAdapter:
    def __init__(self, gptcache_obj: Any) -> None: ...
    def get(self, key: str) -> str | None: ...
    def put(self, key: str, value: str) -> None: ...
    def clear(self) -> None: ...
