"""Built-in scorers + the run_eval driver. See `EvalHarness` in
`litgraph.eval` for higher-level orchestration with reports."""
from __future__ import annotations
from typing import Any, Callable, Iterable, Mapping, Sequence


class LlmJudge:
    def __init__(self, model: Any, system_prompt: str | None = ...) -> None: ...
    def judge(self, prompt: str, response: str) -> Any: ...
    def judge_batch(self, items: Sequence[Mapping[str, str]]) -> list[Any]: ...


class PiiScrubber:
    def __init__(self) -> None: ...
    def scrub(self, text: str) -> str: ...


def contains_all(text: str, needles: Sequence[str]) -> bool: ...
def contains_any(text: str, needles: Sequence[str]) -> bool: ...
def embedding_cosine(a: Sequence[float], b: Sequence[float]) -> float: ...
def exact_match(actual: str, expected: str) -> bool: ...
def exact_match_strict(actual: str, expected: str) -> bool: ...
def jaccard_similarity(a: str, b: str) -> float: ...
def json_validity(text: str) -> bool: ...
def levenshtein(a: str, b: str) -> int: ...
def levenshtein_ratio(a: str, b: str) -> float: ...
def luhn_valid(digits: str) -> bool: ...
def regex_match(text: str, pattern: str) -> bool: ...
def run_eval(
    cases: Iterable[Mapping[str, Any]],
    target: Callable[[Mapping[str, Any]], Any],
    scorers: Mapping[str, Callable[..., Any]],
    max_parallel: int = 4,
) -> Any: ...
