from typing import Any, Callable, Iterator

START: str
END: str

class StateGraph:
    def __init__(self, max_parallel: int = 16, recursion_limit: int = 25) -> None: ...
    def add_node(self, name: str, func: Callable[[dict[str, Any]], Any]) -> None: ...
    def add_edge(self, from_: str, to: str) -> None: ...
    def add_conditional_edges(
        self,
        from_: str,
        router: Callable[[dict[str, Any]], str | list[str]],
    ) -> None: ...
    def interrupt_before(self, node: str) -> None: ...
    def interrupt_after(self, node: str) -> None: ...
    def set_entry(self, node: str) -> None: ...
    def compile(self) -> "CompiledGraph": ...
    def to_mermaid(self) -> str: ...
    def to_ascii(self) -> str: ...

class CompiledGraph:
    def invoke(
        self,
        state: dict[str, Any],
        thread_id: str | None = None,
    ) -> dict[str, Any]: ...
    def resume(
        self,
        thread_id: str,
        update: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def stream(
        self,
        state: dict[str, Any],
        thread_id: str | None = None,
    ) -> "GraphStream": ...
    def to_mermaid(self) -> str: ...
    def to_ascii(self) -> str: ...

class GraphStream:
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
    def __next__(self) -> dict[str, Any]: ...
