"""LCEL-style pipe operator (`|`) for litGraph."""
from __future__ import annotations
from typing import Any, Callable


class Pipe:
    def __init__(self, step: Any) -> None: ...
    def __or__(self, other: object) -> "Pipe": ...
    def __call__(self, input: Any) -> Any: ...
    def invoke(self, input: Any) -> Any: ...


def parallel(*steps: Any) -> Callable[[Any], list[Any]]: ...
