"""Hierarchical / namespaced memory wrapper + DynamoDB / Mongo backends."""
from __future__ import annotations
from typing import Any, Mapping


NS_KEY: str


class NamespacedMemory:
    namespace: str
    def __init__(self, inner: Any, namespace: str) -> None: ...
    def add_user(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_ai(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_tool(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def set_system(self, message: Mapping[str, Any] | str | None) -> None: ...
    def clear(self) -> None: ...
    def messages(self) -> list[Mapping[str, Any]]: ...


class DynamoDBChatMemory:
    table_name: str
    session_id: str
    def __init__(
        self,
        table_name: str,
        session_id: str,
        region_name: str | None = ...,
        endpoint_url: str | None = ...,
    ) -> None: ...
    def add_user(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_ai(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_tool(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def set_system(self, message: Mapping[str, Any] | str | None) -> None: ...
    def clear(self) -> None: ...
    def messages(self) -> list[Mapping[str, Any]]: ...


class MongoChatMemory:
    session_id: str
    def __init__(
        self,
        session_id: str,
        uri: str | None = ...,
        database: str = "litgraph",
        collection_name: str = "chat_messages",
    ) -> None: ...
    def add_user(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_ai(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def add_tool(self, text: str, metadata: Mapping[str, Any] | None = ...) -> None: ...
    def set_system(self, message: Mapping[str, Any] | str | None) -> None: ...
    def clear(self) -> None: ...
    def messages(self) -> list[Mapping[str, Any]]: ...
