from typing import Any, Callable

from .providers import (
    AnthropicChat, BedrockChat, CohereChat, GeminiChat, OpenAIChat,
)

ChatModel = OpenAIChat | AnthropicChat | GeminiChat | BedrockChat | CohereChat

def summarize_conversation(
    model: ChatModel,
    messages: list[dict[str, Any]],
    prior_summary: str | None = None,
) -> str: ...

class BufferMemory:
    def __init__(self, max_messages: int = 20) -> None: ...
    def append(self, message: dict[str, Any]) -> None: ...
    def messages(self) -> list[dict[str, Any]]: ...
    def clear(self) -> None: ...
    def set_system(self, message: dict[str, Any] | None = None) -> None: ...
    def to_bytes(self) -> bytes: ...
    def restore(self, bytes: bytes) -> None: ...
    @staticmethod
    def from_bytes(max_messages: int, bytes: bytes) -> "BufferMemory": ...
    def summarize_and_compact(self, model: ChatModel, summarize_count: int) -> None: ...

class TokenBufferMemory:
    def __init__(
        self,
        max_tokens: int,
        counter: Callable[[dict[str, Any]], int],
    ) -> None: ...
    def append(self, message: dict[str, Any]) -> None: ...
    def messages(self) -> list[dict[str, Any]]: ...
    def clear(self) -> None: ...
    def set_system(self, message: dict[str, Any] | None = None) -> None: ...
    def to_bytes(self) -> bytes: ...
    def restore(self, bytes: bytes) -> None: ...
