from typing import Any

class LoggingMiddleware:
    def __init__(self) -> None: ...

class MessageWindowMiddleware:
    def __init__(self, keep_last: int) -> None: ...

class SystemPromptMiddleware:
    def __init__(self, prompt: str) -> None: ...

class MiddlewareChain:
    def __init__(self) -> None: ...
    def append(self, middleware: Any) -> None: ...
    def with_(self, middleware: Any) -> "MiddlewareChain": ...
    def names(self) -> list[str]: ...
    def __len__(self) -> int: ...

class MiddlewareChat:
    def __init__(self, model: Any, chain: MiddlewareChain) -> None: ...
    def names(self) -> list[str]: ...
