"""Output parsers + format-instruction helpers — all native, all
allocation-tight. See `with_structured_output` for the full
schema-aware path."""
from __future__ import annotations
from typing import Any, Sequence


def boolean_format_instructions() -> str: ...
def comma_list_format_instructions() -> str: ...
def fix_with_llm(raw: str, error: str, instructions: str, model: Any) -> str: ...
def markdown_list_format_instructions() -> str: ...
def numbered_list_format_instructions() -> str: ...
def parse_boolean(text: str) -> bool | None: ...
def parse_comma_list(text: str) -> list[str]: ...
def parse_json_with_retry(
    raw: str,
    model: Any,
    schema_hint: str = "",
    max_retries: int = 1,
) -> Any: ...
def parse_markdown_list(text: str) -> list[str]: ...
def parse_markdown_tables(text: str) -> list[Any]: ...
def parse_nested_xml(text: str) -> Any: ...
def parse_numbered_list(text: str) -> list[str]: ...
def parse_partial_json(text: str) -> Any: ...
def parse_react_step(text: str) -> Any: ...
def parse_xml_tags(text: str, tags: Sequence[str]) -> dict[str, str]: ...
def react_format_instructions(tools: Sequence[Any]) -> str: ...
def repair_partial_json(text: str) -> str: ...
def xml_format_instructions(tags: Sequence[str]) -> str: ...
