from typing import Iterable, Optional

class Skill:
    name: str
    description: str
    content: str
    source: Optional[str]
    def __init__(
        self,
        name: str,
        description: str,
        content: str,
        source: Optional[str] = None,
    ) -> None: ...

class SystemPromptBuilder:
    def __init__(self, base: str) -> None: ...
    def with_agents_md(self, body: str) -> "SystemPromptBuilder": ...
    def with_skill(self, skill: Skill) -> "SystemPromptBuilder": ...
    def with_skills(self, skills: Iterable[Skill]) -> "SystemPromptBuilder": ...
    def with_section(self, heading: str, body: str) -> "SystemPromptBuilder": ...
    def build(self) -> str: ...

def load_agents_md(path: str) -> Optional[str]: ...
def load_skills_dir(dir: str) -> list[Skill]: ...
