from .embeddings import FunctionEmbeddings

class MemoryCache:
    def __init__(self, max_capacity: int = 10_000) -> None: ...
    def clear(self) -> None: ...

class SqliteCache:
    def __init__(self, path: str) -> None: ...
    @staticmethod
    def in_memory() -> "SqliteCache": ...
    def clear(self) -> None: ...

class SemanticCache:
    def __init__(
        self,
        embeddings: FunctionEmbeddings,
        threshold: float = 0.95,
        max_entries: int = 10_000,
    ) -> None: ...
    def __len__(self) -> int: ...
    def clear(self) -> None: ...
