from typing import Any

class CostTracker:
    def __init__(self, prices: dict[str, tuple[float, float]]) -> None: ...
    def usd(self) -> float: ...
    def snapshot(self) -> dict[str, Any]: ...
    def reset(self) -> None: ...
